"""rename pasword column in users table

Revision ID: ebd731e946f6
Revises: ad6372cf2d2d
Create Date: 2025-12-16 16:05:35.877761

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ebd731e946f6"
down_revision: Union[str, Sequence[str], None] = "ad6372cf2d2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=200), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
