"""add room func

Revision ID: 2fb6c88d4e6a
Revises: 032585cd3da6
Create Date: 2025-12-18 18:26:01.081054

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "2fb6c88d4e6a"
down_revision: Union[str, Sequence[str], None] = "032585cd3da6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
