"""booking column type fix

Revision ID: 49070ff1a1de
Revises: c33a18d85a83
Create Date: 2025-12-19 16:20:53.722931

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49070ff1a1de"
down_revision: Union[str, Sequence[str], None] = "c33a18d85a83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bookings", "hotel_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "bookings",
        "check_in_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        "bookings",
        "check_out_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column("bookings", "price", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("bookings", "price", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "bookings",
        "check_out_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "bookings", "check_in_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("bookings", "room_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bookings", "hotel_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("bookings", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
