"""add bookings

Revision ID: 770804a9666d
Revises: 2fb6c88d4e6a
Create Date: 2025-12-19 02:26:09.088630

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "770804a9666d"
down_revision: Union[str, Sequence[str], None] = "2fb6c88d4e6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
