"""empty message

Revision ID: 2278f3f34bd9
Revises: 15466c363e15
Create Date: 2026-01-08 02:06:27.423974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2278f3f34bd9"
down_revision: Union[str, Sequence[str], None] = "15466c363e15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hotels", sa.Column("images", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotels", "images")
    # ### end Alembic commands ###
